---
degree: 'Doctorate'
department: 'Antarctic and SubAntartic Sciences'
degreetype: 'Doctorate' # Replace with degree completing, e.g. Bachelor of Science Honours
gradyear: '2024'
author: 'Mauricio Mardones Inostroza'
title: 'Population dynamics and fishery of krill (*Euphausia superba*) along the Western Antarctic Peninsula'
knit: bookdown::render_book
site: bookdown::bookdown_site
output: torontodown::thesis_pdf
keep_tex: true
# si la quiero en word, descativo torontodown arriba
# output:
#   bookdown::word_document2:
#     toc: true
#     number_sections: true
#     always_allow_html: true
#     reference_docx: custom-reference.docx # opcional si tienes una plantilla
latex_engine: xelatex
bibliography: [bib/ThesisDOCAS_limpio.bib]
csl: csl/apa.csl
link-citations: true
linkcolor: blue
link-bibliography: true
---

\let\cleardoublepage\clearpage

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  error = FALSE,
  fig.align = 'center',
  fig.pos = "htbp",
  fig.show='asis'
)
```

```{r message=FALSE, eval=TRUE}
library(here)
library(kableExtra)
library(ggpubr)
library(tibble)
library(readxl)
library(openxlsx)
library(r4ss)
library(readr)
library(flextable)
library(officer)
library(r4ss)
library(pdftools)
library(magick)
library(here)
#analisis
library(ggsignif)
library(ggrepel)
library(ggpubr)
#library(inlmisc)
library(nortest) #para testear distribucion
library(skimr) #provides a frictionless approach to summary statistics 
library(lubridate)
library(easystats) # multiples unciones analiticas
library(lme4)
library(skimr)
library(readxl)
library(fitdistrplus)
# vizualizacion
library(ggridges)
library(sf)
library(GGally)
library(tidyverse, quietly = TRUE)
library(knitr, quietly = TRUE)
library(kableExtra)
library(raster)
library(egg)
library(car) #Variance inflation Factor
library(ggthemes)
library(sjPlot)
library(GGally)
library(CCAMLRGIS)
library(modelsummary)
library(tinytable)
library(ggcorrplot)
```




